[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
metaplex_core_nft_staking = "3kn7rbPcVMpAVPdc2q2sykSzxRyWmsYZ7fy9fh64q7MM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
